### ISSUE TITLE
conflicting updates

### ISSUE THREAD

**Issue by python-nerd-3** [PVcoders/useless-site#5]
i made an update but i didnt upload it then poley kid made a pull request

**Comment by Compound-codes** [comment]
just saying, the color pallete is disgusting

**Comment by Compound-codes** [comment]
it looks like a hacker website, a scam website, not a fun website.
people would want to get right off here

**Comment by Compound-codes** [comment]
maybe use this palette https://colorhunt.co/palette/e5d9b6a4be7b5f8d4e285430
